/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ApproveInterface extends utils.Interface {
  contractName: "Approve";
  functions: {
    "_FTUser(address,uint256)": FunctionFragment;
    "_NFTPool(uint256)": FunctionFragment;
    "_TokenBNBUser(address)": FunctionFragment;
    "_TokenBUSDUser(address)": FunctionFragment;
    "__FarmingInit(address,address,address,address)": FunctionFragment;
    "addFarmingBUSDPool(uint256)": FunctionFragment;
    "badgeContract()": FunctionFragment;
    "busd()": FunctionFragment;
    "estimateFarmingBUSDPoolReward()": FunctionFragment;
    "harvestFarmingBUSDPoolReward()": FunctionFragment;
    "ico()": FunctionFragment;
    "owner()": FunctionFragment;
    "recipient()": FunctionFragment;
    "removeFarmingBUSDPool(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setFarmingBUSDPool(uint256,uint256,uint256)": FunctionFragment;
    "tokenA()": FunctionFragment;
    "tokenB()": FunctionFragment;
    "tokenBNBPool()": FunctionFragment;
    "tokenBUSDPool()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_FTUser",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_NFTPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_TokenBNBUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_TokenBUSDUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "__FarmingInit",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addFarmingBUSDPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "badgeContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "busd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateFarmingBUSDPoolReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvestFarmingBUSDPoolReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ico", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "recipient", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFarmingBUSDPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFarmingBUSDPool",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenBNBPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBUSDPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "_FTUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_NFTPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_TokenBNBUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_TokenBUSDUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__FarmingInit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFarmingBUSDPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "badgeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "busd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateFarmingBUSDPoolReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "harvestFarmingBUSDPoolReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ico", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recipient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFarmingBUSDPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFarmingBUSDPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenBNBPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBUSDPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AddLiquidityBUSDPool(address,uint256,uint256)": EventFragment;
    "HarvestFarmingBUSDPool(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RemoveLiquidityBUSDPool(address,uint256,uint256)": EventFragment;
    "SetFarmingBUSDPool(uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddLiquidityBUSDPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HarvestFarmingBUSDPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveLiquidityBUSDPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFarmingBUSDPool"): EventFragment;
}

export type AddLiquidityBUSDPoolEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; tokenAmount: BigNumber; bnbAmount: BigNumber }
>;

export type AddLiquidityBUSDPoolEventFilter =
  TypedEventFilter<AddLiquidityBUSDPoolEvent>;

export type HarvestFarmingBUSDPoolEvent = TypedEvent<
  [string, BigNumber],
  { user: string; tokenAAmount: BigNumber }
>;

export type HarvestFarmingBUSDPoolEventFilter =
  TypedEventFilter<HarvestFarmingBUSDPoolEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type RemoveLiquidityBUSDPoolEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { user: string; tokenAmount: BigNumber; bnbAmount: BigNumber }
>;

export type RemoveLiquidityBUSDPoolEventFilter =
  TypedEventFilter<RemoveLiquidityBUSDPoolEvent>;

export type SetFarmingBUSDPoolEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  { timestamp: BigNumber; rate: BigNumber; decimal: BigNumber; roi: BigNumber }
>;

export type SetFarmingBUSDPoolEventFilter =
  TypedEventFilter<SetFarmingBUSDPoolEvent>;

export interface Approve extends BaseContract {
  contractName: "Approve";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ApproveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _FTUser(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { FTBalance: BigNumber; lastUpdate: BigNumber }
    >;

    _NFTPool(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        NFTId: BigNumber;
        ROI: BigNumber;
        FTBalance: BigNumber;
      }
    >;

    _TokenBNBUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokenBalance: BigNumber;
        bnbBalance: BigNumber;
        lastUpdate: BigNumber;
      }
    >;

    _TokenBUSDUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokenBalance: BigNumber;
        busdBalance: BigNumber;
        lastUpdate: BigNumber;
      }
    >;

    __FarmingInit(
      _tokenA: string,
      _tokenB: string,
      _badgeContract: string,
      _busdAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    badgeContract(overrides?: CallOverrides): Promise<[string]>;

    busd(overrides?: CallOverrides): Promise<[string]>;

    estimateFarmingBUSDPoolReward(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    harvestFarmingBUSDPoolReward(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ico(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    recipient(overrides?: CallOverrides): Promise<[string]>;

    removeFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFarmingBUSDPool(
      _rate: BigNumberish,
      _decimal: BigNumberish,
      _roi: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenA(overrides?: CallOverrides): Promise<[string]>;

    tokenB(overrides?: CallOverrides): Promise<[string]>;

    tokenBNBPool(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        ROI: BigNumber;
        rate: BigNumber;
        decimal: BigNumber;
        tokenBalance: BigNumber;
        bnbBalance: BigNumber;
      }
    >;

    tokenBUSDPool(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        ROI: BigNumber;
        rate: BigNumber;
        decimal: BigNumber;
        tokenBalance: BigNumber;
        busdBalance: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _FTUser(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { FTBalance: BigNumber; lastUpdate: BigNumber }
  >;

  _NFTPool(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      NFTId: BigNumber;
      ROI: BigNumber;
      FTBalance: BigNumber;
    }
  >;

  _TokenBNBUser(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      tokenBalance: BigNumber;
      bnbBalance: BigNumber;
      lastUpdate: BigNumber;
    }
  >;

  _TokenBUSDUser(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      tokenBalance: BigNumber;
      busdBalance: BigNumber;
      lastUpdate: BigNumber;
    }
  >;

  __FarmingInit(
    _tokenA: string,
    _tokenB: string,
    _badgeContract: string,
    _busdAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addFarmingBUSDPool(
    _tokenAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  badgeContract(overrides?: CallOverrides): Promise<string>;

  busd(overrides?: CallOverrides): Promise<string>;

  estimateFarmingBUSDPoolReward(overrides?: CallOverrides): Promise<BigNumber>;

  harvestFarmingBUSDPoolReward(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ico(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  recipient(overrides?: CallOverrides): Promise<string>;

  removeFarmingBUSDPool(
    _tokenAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFarmingBUSDPool(
    _rate: BigNumberish,
    _decimal: BigNumberish,
    _roi: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenA(overrides?: CallOverrides): Promise<string>;

  tokenB(overrides?: CallOverrides): Promise<string>;

  tokenBNBPool(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      ROI: BigNumber;
      rate: BigNumber;
      decimal: BigNumber;
      tokenBalance: BigNumber;
      bnbBalance: BigNumber;
    }
  >;

  tokenBUSDPool(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      ROI: BigNumber;
      rate: BigNumber;
      decimal: BigNumber;
      tokenBalance: BigNumber;
      busdBalance: BigNumber;
    }
  >;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _FTUser(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { FTBalance: BigNumber; lastUpdate: BigNumber }
    >;

    _NFTPool(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        NFTId: BigNumber;
        ROI: BigNumber;
        FTBalance: BigNumber;
      }
    >;

    _TokenBNBUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokenBalance: BigNumber;
        bnbBalance: BigNumber;
        lastUpdate: BigNumber;
      }
    >;

    _TokenBUSDUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        tokenBalance: BigNumber;
        busdBalance: BigNumber;
        lastUpdate: BigNumber;
      }
    >;

    __FarmingInit(
      _tokenA: string,
      _tokenB: string,
      _badgeContract: string,
      _busdAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    badgeContract(overrides?: CallOverrides): Promise<string>;

    busd(overrides?: CallOverrides): Promise<string>;

    estimateFarmingBUSDPoolReward(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    harvestFarmingBUSDPoolReward(overrides?: CallOverrides): Promise<void>;

    ico(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    recipient(overrides?: CallOverrides): Promise<string>;

    removeFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFarmingBUSDPool(
      _rate: BigNumberish,
      _decimal: BigNumberish,
      _roi: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenA(overrides?: CallOverrides): Promise<string>;

    tokenB(overrides?: CallOverrides): Promise<string>;

    tokenBNBPool(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        ROI: BigNumber;
        rate: BigNumber;
        decimal: BigNumber;
        tokenBalance: BigNumber;
        bnbBalance: BigNumber;
      }
    >;

    tokenBUSDPool(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        ROI: BigNumber;
        rate: BigNumber;
        decimal: BigNumber;
        tokenBalance: BigNumber;
        busdBalance: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddLiquidityBUSDPool(address,uint256,uint256)"(
      user?: null,
      tokenAmount?: null,
      bnbAmount?: null
    ): AddLiquidityBUSDPoolEventFilter;
    AddLiquidityBUSDPool(
      user?: null,
      tokenAmount?: null,
      bnbAmount?: null
    ): AddLiquidityBUSDPoolEventFilter;

    "HarvestFarmingBUSDPool(address,uint256)"(
      user?: null,
      tokenAAmount?: null
    ): HarvestFarmingBUSDPoolEventFilter;
    HarvestFarmingBUSDPool(
      user?: null,
      tokenAAmount?: null
    ): HarvestFarmingBUSDPoolEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "RemoveLiquidityBUSDPool(address,uint256,uint256)"(
      user?: null,
      tokenAmount?: null,
      bnbAmount?: null
    ): RemoveLiquidityBUSDPoolEventFilter;
    RemoveLiquidityBUSDPool(
      user?: null,
      tokenAmount?: null,
      bnbAmount?: null
    ): RemoveLiquidityBUSDPoolEventFilter;

    "SetFarmingBUSDPool(uint256,uint256,uint256,uint256)"(
      timestamp?: null,
      rate?: null,
      decimal?: null,
      roi?: null
    ): SetFarmingBUSDPoolEventFilter;
    SetFarmingBUSDPool(
      timestamp?: null,
      rate?: null,
      decimal?: null,
      roi?: null
    ): SetFarmingBUSDPoolEventFilter;
  };

  estimateGas: {
    _FTUser(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _NFTPool(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    _TokenBNBUser(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _TokenBUSDUser(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    __FarmingInit(
      _tokenA: string,
      _tokenB: string,
      _badgeContract: string,
      _busdAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    badgeContract(overrides?: CallOverrides): Promise<BigNumber>;

    busd(overrides?: CallOverrides): Promise<BigNumber>;

    estimateFarmingBUSDPoolReward(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    harvestFarmingBUSDPoolReward(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ico(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    recipient(overrides?: CallOverrides): Promise<BigNumber>;

    removeFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFarmingBUSDPool(
      _rate: BigNumberish,
      _decimal: BigNumberish,
      _roi: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenA(overrides?: CallOverrides): Promise<BigNumber>;

    tokenB(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBNBPool(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBUSDPool(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _FTUser(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _NFTPool(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _TokenBNBUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _TokenBUSDUser(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    __FarmingInit(
      _tokenA: string,
      _tokenB: string,
      _badgeContract: string,
      _busdAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    badgeContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    busd(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    estimateFarmingBUSDPoolReward(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    harvestFarmingBUSDPoolReward(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ico(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeFarmingBUSDPool(
      _tokenAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFarmingBUSDPool(
      _rate: BigNumberish,
      _decimal: BigNumberish,
      _roi: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBNBPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBUSDPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
