/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IICOInterface extends utils.Interface {
  contractName: "IICO";
  functions: {
    "getReferal(address)": FunctionFragment;
    "getReferee(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getReferal", values: [string]): string;
  encodeFunctionData(functionFragment: "getReferee", values: [string]): string;

  decodeFunctionResult(functionFragment: "getReferal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getReferee", data: BytesLike): Result;

  events: {};
}

export interface IICO extends BaseContract {
  contractName: "IICO";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IICOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReferal(_referee: string, overrides?: CallOverrides): Promise<[string]>;

    getReferee(
      _referal: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  getReferal(_referee: string, overrides?: CallOverrides): Promise<string>;

  getReferee(_referal: string, overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    getReferal(_referee: string, overrides?: CallOverrides): Promise<string>;

    getReferee(_referal: string, overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    getReferal(_referee: string, overrides?: CallOverrides): Promise<BigNumber>;

    getReferee(_referal: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getReferal(
      _referee: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReferee(
      _referal: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
