/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IICO, IICOInterface } from "../IICO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_referee",
        type: "address",
      },
    ],
    name: "getReferal",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_referal",
        type: "address",
      },
    ],
    name: "getReferee",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IICO__factory {
  static readonly abi = _abi;
  static createInterface(): IICOInterface {
    return new utils.Interface(_abi) as IICOInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IICO {
    return new Contract(address, _abi, signerOrProvider) as IICO;
  }
}
